replicaCount: 1
image:
  repository: "385800116362.dkr.ecr.us-east-1.amazonaws.com/bighill/mlops/training-service"
  tag: "0.0.1"
  pullPolicy: Always
service:
  type: ClusterIP
  healthPort: 5058
env:
  environment: "staging"
  temporalAddress: "temporal:7233"
  temporalNamespace: "default"
  temporalTaskQueue: "training-service"
  kafkaBroker: "kafka:9092"
  kafkaBaseGroupId: "training"
  kafkaAutoOffsetReset: "earliest"
  topic: "training"
  dataRegistrySubscriberTopic: "data_registry"
  dlq: "http://localhost:4566/training-dev-env-queue/"
  baseModel: "local-dev-base-model"
