replicaCount: 1
image:
  repository: "training-service"
  tag: "0.0.1"
  pullPolicy: IfNotPresent
serviceAccount:
  create: false
  name: "training-service"
  annotations: {}
service:
  type: ClusterIP
  healthPort: 5058
ingress:
  enabled: false
  host: ""
  certificateArn: ""
env:
  environment: "local-dev"
  serviceName: "training-service"
  otelExporterEndpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
  temporalAddress: "temporal:7233"
  temporalNamespace: "default"
  temporalTaskQueue: "training-service"
  kafkaBroker: "kafka:9092"
  kafkaGroupId: "training-group"
  topic: "training"
  dataRegistrySubscriberTopic: "data_registry"
  dlq: "http://localhost:4566/training-dev-env-queue/"
  baseModel: "local-dev-base-model"
  executorProvider: "ray"
  rayJobsUrl: "http://ray-head:8265"
  rayTrainingEntrypoint: "python -m training_jobs.train"
  rayEvaluationEntrypoint: "python -m training_jobs.evaluate"
  rayRequestTimeoutSeconds: "30"
  rayPollIntervalSeconds: "30"
  artifactBucketRegion: "local-dev"
  modelUriPrefix: "s3://local-dev-bucket/models"
  evaluationUriPrefix: "s3://local-dev-bucket/evaluations"
  healthcheckCpuThreshold: "80"
  healthcheckFreeMemThreshold: "20"
  healthcheckServiceLatencyThreshold: "5"
  healthcheckMessageBrokerLatencyThreshold: "5"
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "768Mi"
    cpu: "500m"
