apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "inference-service.fullname" . }}-test-connection"
  labels:
    app: {{ include "inference-service.fullname" . }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "inference-service.fullname" . }}:{{ .Values.service.healthPort }}/health']
  restartPolicy: Never
