apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "data-stream-service.fullname" . }}-test-connection"
  labels:
    app: {{ include "data-stream-service.fullname" . }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ["wget"]
      args: ["{{ include "data-stream-service.fullname" . }}:{{ .Values.service.healthPort }}/health"]
  restartPolicy: Never
