replicaCount: 1
image:
  repository: "385800116362.dkr.ecr.eu-west-1.amazonaws.com/bighill/mlops"
  tag: "model-serving-service-0.0.1-staging"
  pullPolicy: Always
service:
  type: ClusterIP
  healthPort: 5061
env:
  environment: "staging"
  backend: "kubernetes"
  vllmImage: "vllm/vllm-openai:latest"
  vllmMultiTenantEnabled: "true"
  vllmRequestTimeoutMs: "5000"
