replicaCount: 1
image:
  repository: "385800116362.dkr.ecr.us-east-1.amazonaws.com/bighill/mlops/model-serving-service"
  tag: "0.0.1"
  pullPolicy: Always
service:
  type: ClusterIP
  healthPort: 5061
env:
  environment: "staging"
  vllmImage: "vllm/vllm-openai:latest"
