{{- if .Values.env.dbCredentialsExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-db-creds" .Values.env.serviceName) .Values.env.dbCredentialsExternalSecret.targetSecretName }}
spec:
  refreshInterval: {{ .Values.env.dbCredentialsExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.env.dbCredentialsExternalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.env.dbCredentialsExternalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ default (printf "%s-db-creds" .Values.env.serviceName) .Values.env.dbCredentialsExternalSecret.targetSecretName }}
  data:
    - secretKey: {{ .Values.env.dbCredentialsSecret.userKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.userKey .Values.env.dbCredentialsExternalSecret.remoteKeys.user | quote }}
    - secretKey: {{ .Values.env.dbCredentialsSecret.passwordKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.passwordKey .Values.env.dbCredentialsExternalSecret.remoteKeys.password | quote }}
    - secretKey: {{ .Values.env.dbCredentialsSecret.nameKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.nameKey .Values.env.dbCredentialsExternalSecret.remoteKeys.name | quote }}
    - secretKey: {{ .Values.env.dbCredentialsSecret.hostKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.hostKey .Values.env.dbCredentialsExternalSecret.remoteKeys.host | quote }}
    - secretKey: {{ .Values.env.dbCredentialsSecret.portKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.portKey .Values.env.dbCredentialsExternalSecret.remoteKeys.port | quote }}
    - secretKey: {{ .Values.env.dbCredentialsSecret.sslmodeKey }}
      remoteRef:
        key: {{ default .Values.env.dbCredentialsSecret.sslmodeKey .Values.env.dbCredentialsExternalSecret.remoteKeys.sslmode | quote }}
{{- end }}
