#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1
. $BIGHILL_ROOT/database/scripts/config.sh $1

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export MODEL_REGISTRY_SERVICE_SERVING_RECONCILIATION_ENABLED=true
    export MODEL_REGISTRY_SERVICE_SERVING_BACKEND=local
    export MODEL_REGISTRY_SERVICE_DLQ=http://localhost:4566/model-registry-dev-env-queue/
    export MODEL_REGISTRY_SERVICE_SERVING_LOCAL_STORE_PATH=$BIGHILL_ROOT/tmp/local_served_models/served_models.json
elif [ "$1" = "staging" ]; then
    export MODEL_REGISTRY_SERVICE_SERVING_RECONCILIATION_ENABLED=true
    export MODEL_REGISTRY_SERVICE_SERVING_BACKEND=kubernetes
    export MODEL_REGISTRY_SERVICE_DLQ=
    export MODEL_REGISTRY_SERVICE_SERVING_LOCAL_STORE_PATH=
elif [ "$1" = "prod" ]; then
    export MODEL_REGISTRY_SERVICE_SERVING_RECONCILIATION_ENABLED=true
    export MODEL_REGISTRY_SERVICE_SERVING_BACKEND=kubernetes
    export MODEL_REGISTRY_SERVICE_DLQ=
    export MODEL_REGISTRY_SERVICE_SERVING_LOCAL_STORE_PATH=
else
    echo "Error: Invalid environment provided to model_registry_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export MODEL_REGISTRY_SERVICE_NAME=model-registry-service
export MODEL_REGISTRY_SERVICE_API_HTTP_PORT=8084
export MODEL_REGISTRY_SERVICE_DB_NAME=bighill_model_registry_db
export MODEL_REGISTRY_SERVICE_DB_USER=bighill_model_registry_db_user
export MODEL_REGISTRY_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export MODEL_REGISTRY_SERVICE_DB_MAX_CONNECTIONS=20
export MODEL_REGISTRY_SERVICE_KAFKA_BASE_GROUP_ID=model-registry
export MODEL_REGISTRY_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export MODEL_REGISTRY_SERVICE_TOPIC=model_registry
export MODEL_REGISTRY_SERVICE_TRAINING_SUBSCRIBER_TOPIC=training
export MODEL_REGISTRY_SERVICE_INGESTION_SUBSCRIBER_TOPIC=ingestion
export MODEL_REGISTRY_SERVICE_TENANT_SUBSCRIBER_TOPIC=tenant
export MODEL_REGISTRY_SERVICE_OUTBOX=postgres
export MODEL_REGISTRY_SERVICE_OUTBOX_RELAY_POLL_MS=250
export MODEL_REGISTRY_SERVICE_OUTBOX_RELAY_BATCH_SIZE=100
export MODEL_REGISTRY_SERVICE_OUTBOX_RELAY_FAILURE_BACKOFF_MS=2000
export MODEL_REGISTRY_SERVICE_SERVING_NAMESPACE=default
export MODEL_REGISTRY_SERVICE_SERVING_LOCAL_RESYNC_SECONDS=30
export MODEL_REGISTRY_SERVICE_SERVING_CRD_GROUP=serving.bighill.io
export MODEL_REGISTRY_SERVICE_SERVING_CRD_VERSION=v1alpha1
export MODEL_REGISTRY_SERVICE_SERVING_CRD_RESOURCE=servedmodels
export MODEL_REGISTRY_SERVICE_SERVING_CRD_KIND=ServedModel
export MODEL_REGISTRY_SERVICE_SERVING_STATUS_POLL_MS=1000
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_PORT=5060
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export MODEL_REGISTRY_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000

# The following are variables set at build time, intended to be used at runtime.
# They are used to set the version in the build in the binary and is available to the binary main package.
# IMPORTANT: This IDs the K8s deployment instance and is used in the templates.
export MODEL_REGISTRY_SERVICE_BUILD_VERSION=0.0.1
