{{- if .Values.rayJobServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rayJobServiceAccount.name | default "training-jobs" }}
  labels:
    app: {{ include "training-service.fullname" . }}
  {{- with .Values.rayJobServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
