image:
  repository: 385800116362.dkr.ecr.us-east-1.amazonaws.com/bighill/mlops
  tag: "data-stream-service-0.0.1-staging"
  pullPolicy: Always

serviceAccount:
  create: true
  name: "data-stream-service"
  annotations: {}

ingress:
  enabled: true
  host: "data-stream.internal.northern.exchange"

env:
  environment: "staging"
  kafkaBroker: "kafka.exchange-staging.svc.cluster.local:9092"
  dlq: "http://localhost:4566/data-stream-dev-env-queue/"
  outbox: ""
  outboxRelayPollMs: "250"
  outboxRelayBatchSize: "100"
  outboxRelayFailureBackoffMs: "2000"
  queryEngineMode: "registry"
  queryEngineDataRoot: "tmp/local_s3_storage"
  queryEngineBinaryPath: "../query_engine/datafusion_query_engine/target/release/datafusion_query_engine"
  queryEngineTimeoutSeconds: "30"
  dataRegistryGrpcAddress: "data-registry-service:7071"
  dataRegistryGrpcDialTimeoutMs: "500"
  dataRegistryGrpcCallTimeoutMs: "15000"
  dataRegistryGrpcRetryCount: "3"
  otelExporterEndpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
