{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "feature-materializer-service.fullname" .) }}
  labels:
    app: {{ include "feature-materializer-service.fullname" . }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
