replicaCount: 1
image:
  repository: "385800116362.dkr.ecr.eu-west-1.amazonaws.com/bighill/mlops/inference-service"
  tag: "0.0.1"
  pullPolicy: Always
service:
  type: ClusterIP
  healthPort: 5059
env:
  environment: "staging"
  dlq: "https://sqs.eu-west-1.amazonaws.com/385800116362/bighill-staging-inference-dlq"
  generationProvider: "vllm"
  generationEndpoint: "http://model-serving-service:8000"
  generationModel: "llama3.1:8b"
  rerankerProvider: "tei"
  rerankerUrl: "http://text-embeddings-inference-reranker:80"
  rerankerModel: "bge-reranker-large"
  queryTransformerProvider: "self_query"
  preferenceDatasetUriTemplate: "s3://bighill-mlops-lakehouse/preferences/{dataset_id}/{preference_dataset_id}.jsonl"
  preferenceDatasetBucketRegion: "eu-west-1"
