DROP TRIGGER IF EXISTS outbox_messages_updated_at ON bighill_inference_db.outbox_messages;
DROP TRIGGER IF EXISTS published_inference_endpoints_updated_at ON bighill_inference_db.published_inference_endpoints;
DROP TRIGGER IF EXISTS preference_dataset_snapshots_updated_at ON bighill_inference_db.preference_dataset_snapshots;
DROP TRIGGER IF EXISTS inference_datasets_updated_at ON bighill_inference_db.inference_datasets;
DROP TRIGGER IF EXISTS inference_models_updated_at ON bighill_inference_db.inference_models;
DROP TRIGGER IF EXISTS tenants_updated_at ON bighill_inference_db.tenants;
DROP TABLE IF EXISTS bighill_inference_db.outbox_messages;
DROP TABLE IF EXISTS bighill_inference_db.agent_tool_invocations;
DROP TABLE IF EXISTS bighill_inference_db.agent_steps;
DROP TABLE IF EXISTS bighill_inference_db.agent_runs;
DROP TABLE IF EXISTS bighill_inference_db.agent_specs;
DROP TABLE IF EXISTS bighill_inference_db.capability_reports;
DROP INDEX IF EXISTS bighill_inference_db.index_published_endpoint_datasets_dataset_id;
DROP TABLE IF EXISTS bighill_inference_db.published_endpoint_datasets;
DROP INDEX IF EXISTS bighill_inference_db.index_published_inference_endpoints_natural_key;
DROP INDEX IF EXISTS bighill_inference_db.index_published_inference_endpoints_serving_model_id;
DROP INDEX IF EXISTS bighill_inference_db.index_published_inference_endpoints_model_id;
DROP INDEX IF EXISTS bighill_inference_db.index_published_inference_endpoints_org_id;
DROP TABLE IF EXISTS bighill_inference_db.published_inference_endpoints;
DROP TABLE IF EXISTS bighill_inference_db.preference_dataset_snapshots;
DROP TABLE IF EXISTS bighill_inference_db.lineage_eval_examples;
DROP TABLE IF EXISTS bighill_inference_db.lineage_eval_sets;
DROP TABLE IF EXISTS bighill_inference_db.preference_examples;
DROP TABLE IF EXISTS bighill_inference_db.inference_feedback;
DROP TABLE IF EXISTS bighill_inference_db.inference_requests;
DROP TABLE IF EXISTS bighill_inference_db.inference_datasets;
DROP TABLE IF EXISTS bighill_inference_db.inference_models;
DROP TABLE IF EXISTS bighill_inference_db.tenants;
DROP TYPE IF EXISTS inference_request_status_enum;
DROP TYPE IF EXISTS processing_profile_enum;
DROP TYPE IF EXISTS catalog_provider_enum;
DROP TYPE IF EXISTS table_format_enum;
DROP TYPE IF EXISTS inference_dataset_processing_state_enum;
DROP TYPE IF EXISTS serving_protocol_enum;
DROP TYPE IF EXISTS inference_model_source_enum;
DROP TYPE IF EXISTS inference_model_kind_enum;
DROP TYPE IF EXISTS inference_model_load_status_enum;
DROP TYPE IF EXISTS inference_model_status_enum;
DROP TYPE IF EXISTS tool_error_type_enum;
DROP TYPE IF EXISTS agent_stop_reason_enum;
DROP TYPE IF EXISTS agent_run_status_enum;
DROP TYPE IF EXISTS agent_endpoint_mode_enum;
DROP TYPE IF EXISTS agent_spec_status_enum;

DROP FUNCTION IF EXISTS updated_at_column();
