replicaCount: 1
image:
  repository: "feature-materializer-service"
  tag: "0.0.1"
  pullPolicy: IfNotPresent
serviceAccount:
  create: false
  name: "feature-materializer-service"
  annotations: {}
service:
  type: ClusterIP
  healthPort: 5057
env:
  environment: "local-dev"
  serviceName: "feature-materializer-service"
  otelExporterEndpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318"
  kafkaBroker: "kafka:9092"
  kafkaGroupId: "feature-materializer-group"
  datasetFileUploadedSubscriberTopic: "dataset_file_uploaded"
  dlq: "http://localhost:4566/feature-materializer-dev-env-queue/"
  outbox: "noop://local"
  outboxRelayPollMs: "250"
  outboxRelayBatchSize: "100"
  outboxRelayFailureBackoffMs: "2000"
  dbHost: "postgres"
  dbPort: "5432"
  dbName: "bighill_feature_materializer_db"
  dbUser: "bighill_feature_materializer_db_user"
  dbPassword: ""
  dbMaxConnections: "20"
  dbSslMode: "require"
  polarisCatalogUrl: "http://polaris-catalog:8181"
  polarisRealm: "POLARIS"
  polarisClientId: ""
  polarisClientSecret: ""
  healthcheckCpuThreshold: "80"
  healthcheckFreeMemThreshold: "20"
  healthcheckServiceLatencyThreshold: "5"
  healthcheckDbLatencyThreshold: "5"
  healthcheckMessageBrokerLatencyThreshold: "5"
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "768Mi"
    cpu: "400m"
