#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1
. $BIGHILL_ROOT/database/scripts/config.sh $1

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export TOOL_CATALOG_SERVICE_DLQ=http://localhost:4566/tool-catalog-dev-env-queue/
elif [ "$1" = "staging" ]; then
    export TOOL_CATALOG_SERVICE_DLQ=
elif [ "$1" = "prod" ]; then
    export TOOL_CATALOG_SERVICE_DLQ=
else
    echo "Error: Invalid environment provided to tool_catalog_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export TOOL_CATALOG_SERVICE_NAME=tool-catalog-service
export TOOL_CATALOG_SERVICE_BUILD_VERSION=0.0.1
export TOOL_CATALOG_SERVICE_API_HTTP_PORT=8091
export TOOL_CATALOG_SERVICE_DB_NAME=bighill_tool_catalog_db
export TOOL_CATALOG_SERVICE_DB_USER=bighill_tool_catalog_db_user
export TOOL_CATALOG_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export TOOL_CATALOG_SERVICE_DB_MAX_CONNECTIONS=10
export TOOL_CATALOG_SERVICE_TOPIC=tool_catalog
export TOOL_CATALOG_SERVICE_OUTBOX=postgres
export TOOL_CATALOG_SERVICE_KAFKA_BASE_GROUP_ID=tool-catalog
export TOOL_CATALOG_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export TOOL_CATALOG_SERVICE_OUTBOX_RELAY_POLL_MS=250
export TOOL_CATALOG_SERVICE_OUTBOX_RELAY_BATCH_SIZE=100
export TOOL_CATALOG_SERVICE_OUTBOX_RELAY_FAILURE_BACKOFF_MS=2000
export TOOL_CATALOG_SERVICE_MCP_VERIFY_TIMEOUT_SECONDS=5
export TOOL_CATALOG_SERVICE_HEALTHCHECK_PORT=5071
export TOOL_CATALOG_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export TOOL_CATALOG_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export TOOL_CATALOG_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export TOOL_CATALOG_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export TOOL_CATALOG_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export TOOL_CATALOG_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export TOOL_CATALOG_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export TOOL_CATALOG_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000
export TOOL_CATALOG_SERVICE_LIFECYCLE_READINESS_TIMEOUT_SECONDS=30
export TOOL_CATALOG_SERVICE_LIFECYCLE_DRAIN_TIMEOUT_SECONDS=30
export TOOL_CATALOG_SERVICE_LIFECYCLE_CLOSE_TIMEOUT_SECONDS=10
