#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export TRAINING_SERVICE_TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-localhost:7233}
    export TRAINING_SERVICE_TRAINING_TRIGGER_ENABLED=false
elif [ "$1" = "staging" ]; then
    export TRAINING_SERVICE_TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-temporal:7233}
    export TRAINING_SERVICE_TRAINING_TRIGGER_ENABLED=true
elif [ "$1" = "prod" ]; then
    export TRAINING_SERVICE_TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-temporal:7233}
    export TRAINING_SERVICE_TRAINING_TRIGGER_ENABLED=true
else
    echo "Error: Invalid environment provided to training_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export TRAINING_SERVICE_NAME=training-service
export TRAINING_SERVICE_TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE:-default}
export TRAINING_SERVICE_TEMPORAL_TASK_QUEUE=training-service
export TRAINING_SERVICE_KAFKA_BASE_GROUP_ID=training
export TRAINING_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export TRAINING_SERVICE_TOPIC=training
export TRAINING_SERVICE_INFERENCE_SUBSCRIBER_TOPIC=inference
export TRAINING_SERVICE_DLQ=http://localhost:4566/training-dev-env-queue/
export TRAINING_SERVICE_API_HTTP_PORT=8085
export TRAINING_SERVICE_HTTP_CLIENT_TIMEOUT_SECONDS=10
export TRAINING_SERVICE_EVALUATION_PROFILE_NAME=ragas-default@v1
export TRAINING_SERVICE_EVALUATION_PROFILE=smoke
export TRAINING_SERVICE_DPO_TRAINING_PROFILE_NAME=dpo-default@v1
export TRAINING_SERVICE_DPO_EVALUATION_PROFILE_NAME=dpo-default@v1
export TRAINING_SERVICE_DPO_EVALUATION_PROFILE='{"metric_suite":"preference","evaluator_name":"pairwise-judge","evaluator_version":"v1"}'
export TRAINING_SERVICE_TRAINING_PROFILE_NAME=sft-default@v1
export TRAINING_SERVICE_TRAINING_PROFILE_TRAINER=sft
export TRAINING_SERVICE_TRAINING_PROFILE_ADAPTER=qlora
export TRAINING_SERVICE_TRAINING_PROFILE_QUANTIZATION=4bit
export TRAINING_SERVICE_TRAINING_PROFILE_PREFERENCE_DATASET_URI=
export TRAINING_SERVICE_TRAINING_PROFILE_DPO_BETA=0.1
export TRAINING_SERVICE_TRAINING_PROFILE_SEQUENCE_LENGTH=2048
export TRAINING_SERVICE_TRAINING_PROFILE_SAMPLE_PACKING=true
export TRAINING_SERVICE_TRAINING_PROFILE_LEARNING_RATE=0.0002
export TRAINING_SERVICE_TRAINING_PROFILE_EPOCHS=3
export TRAINING_SERVICE_TRAINING_PROFILE_MICRO_BATCH_SIZE=1
export TRAINING_SERVICE_TRAINING_PROFILE_GRADIENT_ACCUMULATION_STEPS=4
export TRAINING_SERVICE_TRAINING_PROFILE_LORA_R=16
export TRAINING_SERVICE_TRAINING_PROFILE_LORA_ALPHA=32
export TRAINING_SERVICE_EXECUTOR_PROVIDER=kuberay
export TRAINING_SERVICE_RAY_JOBS_URL=http://localhost:8265
export TRAINING_SERVICE_RAY_TRAINING_ENTRYPOINT="python -m training_jobs.train"
export TRAINING_SERVICE_RAY_EVALUATION_ENTRYPOINT="python -m training_jobs.evaluate"
export TRAINING_SERVICE_AXOLOTL_COMMAND="axolotl train"
export TRAINING_SERVICE_RAY_REQUEST_TIMEOUT_SECONDS=30
export TRAINING_SERVICE_RAY_POLL_INTERVAL_SECONDS=30
export TRAINING_SERVICE_KUBERAY_NAMESPACE=default
export TRAINING_SERVICE_KUBERAY_RAY_VERSION=2.46.0
export TRAINING_SERVICE_KUBERAY_IMAGE=training-jobs:0.0.1
export TRAINING_SERVICE_KUBERAY_IMAGE_PULL_POLICY=IfNotPresent
export TRAINING_SERVICE_KUBERAY_SERVICE_ACCOUNT=training-jobs
export TRAINING_SERVICE_KUBERAY_TTL_SECONDS_AFTER_FINISHED=3600
export TRAINING_SERVICE_KUBERAY_WORKER_REPLICAS=1
export TRAINING_SERVICE_KUBERAY_CPU=1
export TRAINING_SERVICE_KUBERAY_MEMORY=4Gi
export TRAINING_SERVICE_KUBERAY_GPU_RESOURCE=nvidia.com/gpu
export TRAINING_SERVICE_KUBERAY_GPU=1
export TRAINING_SERVICE_ARTIFACT_BUCKET_REGION=eu-west-1
export TRAINING_SERVICE_MODEL_URI_PREFIX=s3://local-dev-bucket/models
export TRAINING_SERVICE_EVALUATION_URI_PREFIX=s3://local-dev-bucket/evaluations
export TRAINING_SERVICE_SERVING_TARGET=
export TRAINING_SERVICE_SERVING_MODEL=
export TRAINING_SERVICE_SERVING_LOAD_STATUS=NOT_LOADED
export TRAINING_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export TRAINING_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export TRAINING_SERVICE_HEALTHCHECK_PORT=5058
export TRAINING_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export TRAINING_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export TRAINING_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export TRAINING_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export TRAINING_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000

# The following are variables set at build time, intended to be used at runtime.
# They are used to set the version in the build in the binary and is available to the binary main package.
# IMPORTANT: This IDs the K8s deployment instance and is used in the templates.
export TRAINING_SERVICE_BUILD_VERSION=0.0.1
