#!/usr/bin/env bash

# Env type is set in shared lib for logging
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
. "$PROJECT_ROOT/shared_lib/scripts/config.sh" "$1"
. "$PROJECT_ROOT/database/scripts/config.sh" "$1"

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export PROFILE_SERVICE_DLQ=http://localhost:4566/profile-dev-env-queue/
    export PROFILE_SERVICE_OUTBOX=postgres
    export PROFILE_SERVICE_REDIS_ADDRESS=localhost:6379
    export PROFILE_SERVICE_USE_STAGING_TEST_EMAIL_TOKEN=true
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_ID=""
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_SECRET=""
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_ID=""
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_SECRET=""
elif [ "$1" = "staging" ]; then
    export PROFILE_SERVICE_DLQ=http://localhost:4566/profile-dev-env-queue/ # TODO
    export PROFILE_SERVICE_OUTBOX=postgres
    export PROFILE_SERVICE_REDIS_ADDRESS=redis:6379
    export PROFILE_SERVICE_USE_STAGING_TEST_EMAIL_TOKEN=true
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_ID="308109649261-hvbtodmtpegm0gp53ovjchu8j0v6k3i1.apps.googleusercontent.com"
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_SECRET="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"
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_ID=""
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_SECRET=""

elif [ "$1" = "prod" ]; then
    export PROFILE_SERVICE_DLQ="" # TODO
    export PROFILE_SERVICE_OUTBOX=postgres
    export PROFILE_SERVICE_REDIS_ADDRESS=redis:6379
    export PROFILE_SERVICE_USE_STAGING_TEST_EMAIL_TOKEN=false
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_ID="" # TODO
    export PROFILE_SERVICE_OAUTH_GOOGLE_CLIENT_SECRET=""
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_ID=""
    export PROFILE_SERVICE_OAUTH_DISCORD_CLIENT_SECRET=""
else
    echo "Error: Invalid environment provided to profile_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi


export PROFILE_SERVICE_HTTP_PORT=8082
export PROFILE_SERVICE_NAME=profile-service
export PROFILE_SERVICE_BUILD_VERSION=0.0.1

export PROFILE_SERVICE_DB_NAME=bighill_profile_db
export PROFILE_SERVICE_DB_USER=bighill_profile_db_user
export PROFILE_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export PROFILE_SERVICE_DB_MAX_CONNECTIONS=60

export PROFILE_SERVICE_REDIS_USERNAME=""
export PROFILE_SERVICE_REDIS_PASSWORD=""

export PROFILE_SERVICE_AUTH_EXPIRATION_MINUTES=1440
export PROFILE_SERVICE_EMAIL_VALIDATION_TTL_MINUTES=60
export PROFILE_SERVICE_OAUTH_STATE_TTL_MINUTES=10

export PROFILE_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export PROFILE_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=10
export PROFILE_SERVICE_HEALTHCHECK_PORT=5052
export PROFILE_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5

export PROFILE_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export PROFILE_SERVICE_HEALTHCHECK_KAFKA_LATENCY_THRESHOLD_SECONDS=2
export PROFILE_SERVICE_KAFKA_GROUP_ID=profile-group
export PROFILE_SERVICE_KAFKA_PUBLISHER_TOPIC=profile
export PROFILE_SERVICE_OUTBOX_RELAY_POLL_MS=250
export PROFILE_SERVICE_OUTBOX_RELAY_BATCH_SIZE=100
export PROFILE_SERVICE_OUTBOX_RELAY_FAILURE_BACKOFF_MS=2000

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export PROFILE_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=100
    export PROFILE_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=10
fi
