replicaCount: 1
image:
  repository: "tool-service"
  tag: "0.0.1"
  pullPolicy: IfNotPresent
env:
  environment: "staging"
  dbCredentialsSecret:
    name: "aurora-creds-staging"
    userKey: "bighill_tool_db_user"
    passwordKey: "bighill_tool_db_password"
    hostKey: "pg_host"
    portKey: "pg_port"
    sslmodeKey: "pg_sslmode"
    nameKey: "bighill_tool_db"
  httpToolAllowedHosts: ""
