#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1
. $BIGHILL_ROOT/database/scripts/config.sh $1

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export INFERENCE_SERVICE_PREFERENCE_DATASET_BUCKET_REGION=local-dev
    export INFERENCE_SERVICE_QUERY_TRANSFORMER_REQUEST_TIMEOUT_SECONDS=5
    true
elif [ "$1" = "staging" ]; then
    export INFERENCE_SERVICE_PREFERENCE_DATASET_BUCKET_REGION=eu-west-1
    export INFERENCE_SERVICE_QUERY_TRANSFORMER_REQUEST_TIMEOUT_SECONDS=30
    true
elif [ "$1" = "prod" ]; then
    export INFERENCE_SERVICE_PREFERENCE_DATASET_BUCKET_REGION=eu-west-1
    export INFERENCE_SERVICE_QUERY_TRANSFORMER_REQUEST_TIMEOUT_SECONDS=30
    true
else
    echo "Error: Invalid environment provided to inference_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export INFERENCE_SERVICE_NAME=inference-service
export INFERENCE_SERVICE_DB_NAME=bighill_inference_db
export INFERENCE_SERVICE_DB_USER=bighill_inference_db_user
export INFERENCE_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export INFERENCE_SERVICE_DB_MAX_CONNECTIONS=20
export INFERENCE_SERVICE_API_GRPC_PORT=7073
export INFERENCE_SERVICE_KAFKA_BASE_GROUP_ID=inference
export INFERENCE_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export INFERENCE_SERVICE_MODEL_REGISTRY_SUBSCRIBER_TOPIC=model_registry
export INFERENCE_SERVICE_DATA_REGISTRY_SUBSCRIBER_TOPIC=data_registry
export INFERENCE_SERVICE_TENANT_SUBSCRIBER_TOPIC=tenant
export INFERENCE_SERVICE_PREFERENCE_DATASET_TOPIC=inference
export INFERENCE_SERVICE_OUTBOX=postgres
export INFERENCE_SERVICE_OUTBOX_RELAY_POLL_MS=250
export INFERENCE_SERVICE_OUTBOX_RELAY_FAILURE_BACKOFF_MS=2000
export INFERENCE_SERVICE_OUTBOX_RELAY_BATCH_SIZE=100
export INFERENCE_SERVICE_DLQ=http://localhost:4566/inference-dev-env-queue/
export INFERENCE_SERVICE_FEATURE_MATERIALIZER_GRPC_ADDRESS=localhost:7072
export INFERENCE_SERVICE_FEATURE_MATERIALIZER_GRPC_DIAL_TIMEOUT_MS=500
export INFERENCE_SERVICE_FEATURE_MATERIALIZER_GRPC_CALL_TIMEOUT_MS=15000
export INFERENCE_SERVICE_FEATURE_MATERIALIZER_GRPC_RETRY_COUNT=3
export INFERENCE_SERVICE_GENERATION_REQUEST_TIMEOUT_SECONDS=60
export INFERENCE_SERVICE_GENERATION_MAX_OUTPUT_TOKENS=256
export INFERENCE_SERVICE_RERANKER_PROVIDER=tei
export INFERENCE_SERVICE_RERANKER_URL=http://localhost:8080
export INFERENCE_SERVICE_RERANKER_MODEL=bge-reranker-large
export INFERENCE_SERVICE_RERANKER_REQUEST_TIMEOUT_SECONDS=30
export INFERENCE_SERVICE_RERANKER_CANDIDATE_MULTIPLIER=5
export INFERENCE_SERVICE_RAG_MERGE_STRATEGY=reranker
export INFERENCE_SERVICE_QUERY_TRANSFORMER_PROVIDER=self_query
export INFERENCE_SERVICE_PREFERENCE_DATASET_EXPORT_ENABLED=false
export INFERENCE_SERVICE_PREFERENCE_DATASET_URI_TEMPLATE=s3://local-dev-bucket/preferences/{dataset_id}/{preference_dataset_id}.jsonl
export INFERENCE_SERVICE_PREFERENCE_DATASET_MIN_EXAMPLES=1
export INFERENCE_SERVICE_PREFERENCE_DATASET_LIMIT=1000
export INFERENCE_SERVICE_PREFERENCE_DATASET_UPLOAD_PART_SIZE_MB=10
export INFERENCE_SERVICE_PROMPT_STRATEGY_VERSION=rag-prompt-v1
export INFERENCE_SERVICE_PROMPT_MAX_CONTEXT_TOKENS=3000
export INFERENCE_SERVICE_PROMPT_MAX_CONTEXT_CHUNKS=8
export INFERENCE_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export INFERENCE_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export INFERENCE_SERVICE_HEALTHCHECK_PORT=5059
export INFERENCE_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export INFERENCE_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export INFERENCE_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export INFERENCE_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export INFERENCE_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export INFERENCE_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000

# The following are variables set at build time, intended to be used at runtime.
# They are used to set the version in the build in the binary and is available to the binary main package.
# IMPORTANT: This IDs the K8s deployment instance and is used in the templates.
export INFERENCE_SERVICE_BUILD_VERSION=0.0.1
