apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-registry-service.fullname" . }}
  labels:
    app: {{ include "data-registry-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    app: {{ include "data-registry-service.fullname" . }}
