{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "model-serving-service.fullname" . }}
rules:
  - apiGroups: ["serving.bighill.io"]
    resources: ["servedmodels"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["serving.bighill.io"]
    resources: ["servedmodels/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["serving.bighill.io"]
    resources: ["baseruntimes"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["serving.bighill.io"]
    resources: ["baseruntimes/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "model-serving-service.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "model-serving-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (include "model-serving-service.fullname" .) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
