apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-serving-service.fullname" . }}
  labels:
    app: {{ include "model-serving-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "model-serving-service.fullname" . }}
  ports:
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
