apiVersion: v1
kind: Service
metadata:
  name: {{ include "tool-service.fullname" . }}
  labels:
    app: {{ include "tool-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    app: {{ include "tool-service.fullname" . }}
