#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1
. $BIGHILL_ROOT/database/scripts/config.sh $1

resolve_huggingface_e2e_python() {
    if [ -n "${BIGHILL_E2E_HUGGINGFACE_PYTHON:-}" ]; then
        echo "$BIGHILL_E2E_HUGGINGFACE_PYTHON"
        return
    fi
    PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"
    if [ -x "$PYENV_ROOT/versions/3.11.9/bin/python" ]; then
        echo "$PYENV_ROOT/versions/3.11.9/bin/python"
        return
    fi
    if command -v python3 >/dev/null 2>&1; then
        command -v python3
        return
    fi
    if command -v python >/dev/null 2>&1; then
        command -v python
        return
    fi
    echo "python"
}

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export INGESTION_SERVICE_FILES_BUCKET_REGION=local-dev
    export INGESTION_SERVICE_FILES_BUCKET_NAME=local-dev-bucket
    export INGESTION_SERVICE_DLQ=http://localhost:4566/ingestion-dev-env-queue/
    export INGESTION_SERVICE_OUTBOX=postgres
    export INGESTION_SERVICE_REDIS_ADDRESS=localhost:6379
    export BIGHILL_LOCAL_S3_STORAGE_DIR=$BIGHILL_ROOT/tmp/local_s3_storage
elif [ "$1" = "staging" ]; then
    export INGESTION_SERVICE_FILES_BUCKET_REGION=${AWS_DEFAULT_REGION}
    export INGESTION_SERVICE_FILES_BUCKET_NAME=adt-datalake-rawdata-prod-255525589248-eu-west-1 # TODO
    export INGESTION_SERVICE_DLQ=http://localhost:4566/ingestion-dev-env-queue/ # TODO
    export INGESTION_SERVICE_OUTBOX=postgres
    export INGESTION_SERVICE_REDIS_ADDRESS=redis:6379
elif [ "$1" = "prod" ]; then
    export INGESTION_SERVICE_FILES_BUCKET_REGION=${AWS_DEFAULT_REGION}
    export INGESTION_SERVICE_FILES_BUCKET_NAME=adt-datalake-rawdata-prod-255525589248-eu-west-1
    export INGESTION_SERVICE_DLQ="" # TODO
    export INGESTION_SERVICE_OUTBOX=postgres
    export INGESTION_SERVICE_REDIS_ADDRESS=redis:6379
else
    echo "Error: Invalid environment provided to ingestion_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export INGESTION_SERVICE_FILE_MAX_SIZE_MB=2000
export INGESTION_SERVICE_DIRECT_UPLOAD_MAX_SIZE_MB=5
export INGESTION_SERVICE_UPLOAD_SESSION_TTL_SECONDS=900
export INGESTION_SERVICE_UPLOAD_VALIDATION_READ_MAX_SIZE_MB=5
export INGESTION_SERVICE_FILES_UPLOAD_PART_SIZE_MB=${AWS_DEFAULT_UPLOAD_PART_SIZE_MB:-10}
export INGESTION_SERVICE_DB_NAME=bighill_ingestion_db
export INGESTION_SERVICE_DB_USER=bighill_ingestion_db_user
export INGESTION_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export INGESTION_SERVICE_DB_MAX_CONNECTIONS=20
export INGESTION_SERVICE_API_HTTP_PORT=8086
export INGESTION_SERVICE_HTTP_READ_TIMEOUT_SECONDS=30
export INGESTION_SERVICE_HTTP_WRITE_TIMEOUT_SECONDS=1200
export INGESTION_SERVICE_HTTP_IDLE_TIMEOUT_SECONDS=120
export INGESTION_SERVICE_NAME=ingestion-service
export INGESTION_SERVICE_REDIS_USERNAME=""
export INGESTION_SERVICE_REDIS_PASSWORD=""
export INGESTION_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export INGESTION_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export INGESTION_SERVICE_HEALTHCHECK_PORT=5056
export INGESTION_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export INGESTION_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export INGESTION_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export INGESTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export INGESTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export INGESTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000
export INGESTION_SERVICE_KAFKA_BASE_GROUP_ID=ingestion
export INGESTION_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export INGESTION_SERVICE_TOPIC=ingestion
export INGESTION_SERVICE_DATA_REGISTRY_SUBSCRIBER_TOPIC=data_registry
export INGESTION_SERVICE_PROFILE_SUBSCRIBER_TOPIC=profile
export INGESTION_SERVICE_OUTBOX_RELAY_POLL_MS=250
export INGESTION_SERVICE_OUTBOX_RELAY_BATCH_SIZE=100
export INGESTION_SERVICE_OUTBOX_RELAY_FAILURE_BACKOFF_MS=2000
export INGESTION_SERVICE_HUGGINGFACE_TOKEN_ENCRYPTION_KEY=${INGESTION_SERVICE_HUGGINGFACE_TOKEN_ENCRYPTION_KEY:-01234567890123456789012345678901}
if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_MODE=${INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_MODE:-command}
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_WORKING_DIRECTORY=$BIGHILL_ROOT/training_service/training_jobs
    HUGGINGFACE_E2E_PYTHON=$(resolve_huggingface_e2e_python)
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_COMMAND="$HUGGINGFACE_E2E_PYTHON -m training_jobs.model_onboard"
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_TIMEOUT_SECONDS=1200
else
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_MODE=${INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_MODE:-kubernetes}
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_WORKING_DIRECTORY=
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_COMMAND="python -m training_jobs.model_onboard"
    export INGESTION_SERVICE_HUGGINGFACE_DOWNLOAD_TIMEOUT_SECONDS=1200
fi
export INGESTION_SERVICE_HUGGINGFACE_OUTPUT_URI=${INGESTION_SERVICE_HUGGINGFACE_OUTPUT_URI:-"s3://${INGESTION_SERVICE_FILES_BUCKET_NAME}/models/huggingface"}
export INGESTION_SERVICE_HUGGINGFACE_JOB_NAMESPACE=${INGESTION_SERVICE_HUGGINGFACE_JOB_NAMESPACE:-default}
export INGESTION_SERVICE_HUGGINGFACE_JOB_IMAGE=${INGESTION_SERVICE_HUGGINGFACE_JOB_IMAGE:-training-jobs:0.0.1}
export INGESTION_SERVICE_HUGGINGFACE_JOB_IMAGE_PULL_POLICY=${INGESTION_SERVICE_HUGGINGFACE_JOB_IMAGE_PULL_POLICY:-IfNotPresent}
export INGESTION_SERVICE_HUGGINGFACE_JOB_SERVICE_ACCOUNT=${INGESTION_SERVICE_HUGGINGFACE_JOB_SERVICE_ACCOUNT:-ingestion-service}
export INGESTION_SERVICE_HUGGINGFACE_JOB_TTL_SECONDS_AFTER_FINISHED=${INGESTION_SERVICE_HUGGINGFACE_JOB_TTL_SECONDS_AFTER_FINISHED:-3600}
export INGESTION_SERVICE_HUGGINGFACE_JOB_BACKOFF_LIMIT=${INGESTION_SERVICE_HUGGINGFACE_JOB_BACKOFF_LIMIT:-0}
export INGESTION_SERVICE_HUGGINGFACE_JOB_CPU=${INGESTION_SERVICE_HUGGINGFACE_JOB_CPU:-1}
export INGESTION_SERVICE_HUGGINGFACE_JOB_MEMORY=${INGESTION_SERVICE_HUGGINGFACE_JOB_MEMORY:-4Gi}
export INGESTION_SERVICE_HUGGINGFACE_JOB_POLL_INTERVAL_SECONDS=${INGESTION_SERVICE_HUGGINGFACE_JOB_POLL_INTERVAL_SECONDS:-10}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_RESOURCE_ID=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_RESOURCE_ID:-INGESTION_SERVICE_MODEL_RESOURCE_ID}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_MODEL_NAME=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_MODEL_NAME:-INGESTION_SERVICE_MODEL_NAME}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_MODEL_VERSION=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_MODEL_VERSION:-INGESTION_SERVICE_MODEL_VERSION}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_BASE_MODEL=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_BASE_MODEL:-INGESTION_SERVICE_MODEL_BASE_MODEL}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_ARTIFACT_TYPE=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_ARTIFACT_TYPE:-INGESTION_SERVICE_MODEL_ARTIFACT_TYPE}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_ARTIFACT_FORMAT=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_ARTIFACT_FORMAT:-INGESTION_SERVICE_MODEL_ARTIFACT_FORMAT}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_FILE_NAME=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_FILE_NAME:-INGESTION_SERVICE_HUGGINGFACE_FILE}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_REPO_ID=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_REPO_ID:-INGESTION_SERVICE_HUGGINGFACE_REPO_ID}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_REVISION=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_REVISION:-INGESTION_SERVICE_HUGGINGFACE_REVISION}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_TOKEN=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_TOKEN:-INGESTION_SERVICE_HUGGINGFACE_TOKEN}
export INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_OUTPUT_URI=${INGESTION_SERVICE_HUGGINGFACE_JOB_ENV_OUTPUT_URI:-INGESTION_SERVICE_HUGGINGFACE_OUTPUT_URI}


# The following are variables set at build time, intended to be used at runtime.
# They are used to set the version in the build in the binary and is available to the binary main package.
# It is then is used to identify the service instance in the logs.
# IMPORTANT: This IDs the K8s deployment instance and is used in the templates.
export INGESTION_SERVICE_BUILD_VERSION=0.0.1
