#! /usr/bin/env sh

BIGHILL_ROOT=$(git rev-parse --show-toplevel)
. $BIGHILL_ROOT/shared_lib/scripts/config.sh $1
. $BIGHILL_ROOT/database/scripts/config.sh $1

if [ "$1" = "local-dev" ] || [ "$1" = "cicd" ]; then
    export TOOL_EXECUTION_SERVICE_HTTP_TOOL_ALLOWED_HOSTS=localhost,127.0.0.1
    export TOOL_EXECUTION_SERVICE_ALLOWED_ORG_IDS=11111111-1111-1111-1111-111111111111
elif [ "$1" = "staging" ]; then
    export TOOL_EXECUTION_SERVICE_HTTP_TOOL_ALLOWED_HOSTS=
    export TOOL_EXECUTION_SERVICE_ALLOWED_ORG_IDS=
elif [ "$1" = "prod" ]; then
    export TOOL_EXECUTION_SERVICE_HTTP_TOOL_ALLOWED_HOSTS=
    export TOOL_EXECUTION_SERVICE_ALLOWED_ORG_IDS=
else
    echo "Error: Invalid environment provided to tool_execution_service config"
    echo "Usage: './config.sh [local-dev|cicd|staging|prod]'"
    exit 1
fi

export TOOL_EXECUTION_SERVICE_NAME=tool-execution-service
export TOOL_EXECUTION_SERVICE_DB_NAME=bighill_tool_execution_db
export TOOL_EXECUTION_SERVICE_DB_USER=bighill_tool_execution_db_user
export TOOL_EXECUTION_SERVICE_DB_PASSWORD=$BIGHILL_DB_PASSWORD
export TOOL_EXECUTION_SERVICE_DB_MAX_CONNECTIONS=20
export TOOL_EXECUTION_SERVICE_GRPC_PORT=7084
export TOOL_EXECUTION_SERVICE_DLQ=http://localhost:4566/tool-execution-dev-env-queue/
export TOOL_EXECUTION_SERVICE_KAFKA_BASE_GROUP_ID=tool-execution
export TOOL_EXECUTION_SERVICE_KAFKA_AUTO_OFFSET_RESET=earliest
export TOOL_EXECUTION_SERVICE_TOOL_CATALOG_SUBSCRIBER_TOPIC=tool_catalog
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_PORT=5065
export TOOL_EXECUTION_SERVICE_HTTP_TOOL_TIMEOUT_MS=1500
export TOOL_EXECUTION_SERVICE_HTTP_TOOL_MAX_RESPONSE_BYTES=65536
export TOOL_EXECUTION_SERVICE_PINNED_MCP_SERVER_ENDPOINT=
export TOOL_EXECUTION_SERVICE_PINNED_MCP_SERVER_TRANSPORT=http
export TOOL_EXECUTION_SERVICE_PINNED_MCP_TOOL_NAMES=
export TOOL_EXECUTION_SERVICE_PINNED_MCP_CREDENTIAL_REF=
export TOOL_EXECUTION_SERVICE_PINNED_MCP_ALLOWED_ORG_IDS=
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_CPU_THRESHOLD_PERCENT=80
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_FREE_MEM_THRESHOLD_PERCENT=20
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_DB_LATENCY_THRESHOLD_SECONDS=5
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_SERVICE_LATENCY_THRESHOLD_SECONDS=5
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_MSG_BROKER_LATENCY_THRESHOLD_SECONDS=5
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_POLL_SILENCE_SECONDS=30
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_PROGRESS_SILENCE_SECONDS=90
export TOOL_EXECUTION_SERVICE_HEALTHCHECK_MESSAGE_BROKER_SUBSCRIBER_MAX_LAG=100000
export TOOL_EXECUTION_SERVICE_BUILD_VERSION=0.0.1
